### PR TITLE
Upgrade Substrate / Polkadot / Cumulus crates

### PR DESCRIPTION
**Pull request by Rizziepit**
I'm upgrading the parachain's dependencies in this PR to fix some benchmarking issues. Specifically, I can't generate a valid implementation of `frame_system::WeightInfo` because `frame-system-benchmarking` and `frame-system` are in an inconsistent state. A newer version of `frame-benchmarking` has also been released.

All unit and e2e tests pass. Note that e2e test packages have been upgraded.

### CODE REVIEW

**Review by vgeddes — APPROVED** [review]
LGTM!

**Comment by vgeddes** [comment]
Looks great! A couple of things:

1) Can you update https://github.com/Snowfork/polkadot-ethereum/blob/main/test/README.md#setup with the new revision of polkadot we now depend on? You can find it by looking through Cargo.lock and seeing the revision of the `polkadot-*` deps.

2) Minor ask, can you run cargo update again? As there are now quite a few changes to cumulus/rococo-v1 since you last updated (to cumulus `b9b9cb`). If it causes problems or new incompatibilities, then we can defer of course.

**Comment by Rizziepit** [comment]
> Minor ask, can you run cargo update again? As there are now quite a few changes to cumulus/rococo-v1 since you last updated (to cumulus b9b9cb). If it causes problems or new incompatibilities, then we can defer of course.

Sure. Let's see how it goes

**Comment by Rizziepit** [comment]
I tried updating but cumulus / polkadot / substrate seem to be in an inconsistent state. Let's give it some time before updating again. The chain spec generated by polkadot-launch is missing a `beefy` entry. I also noticed [this commit](https://github.com/paritytech/polkadot/commit/a67612b3fc4bca05c324032faa9108a414e9be61) which might be related. Output from test/scripts/start-services.sh:
```
Starting Ganache
wait-for-it.sh: waiting 20 seconds for localhost:8545
wait-for-it.sh: localhost:8545 is available after 0 seconds
Deploying contracts
~/polkadot-ethereum/ethereum ~/polkadot-ethereum/test

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Network up to date.
Generating configuration from contracts
Using network 'e2e_test'.

~/polkadot-ethereum/test
Wrote configuration to /tmp/artemis-config-ecT
Starting Parachain
~/polkadot-ethereum/parachain ~/polkadot-ethereum/test
    Finished release [optimized] target(s) in 0.60s
Generating Parachain spec
2021-04-06 23:27:58 Building chain spec    
Inserting Ganache chain info into genesis spec
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1487    0  1403  100    84   456k  28000 --:--:-- --:--:-- --:--:--  484k
Writing Polkadot configuration
~/polkadot-ethereum/test
wait-for-it.sh: waiting 20 seconds for localhost:11144
2021-04-06 23:28:00  Building chain spec    
Starting with a fresh authority set:
Added Authority alice
Added Authority bob
2021-04-06 23:28:01  Building chain spec    
Error: 
   0: Other: Error parsing spec file: missing field `beefy` at line 98 column 15

Location:
   src/main.rs:25

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Starting alice...
Starting bob...
2021-04-06 23:28:02          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-04-06 23:28:03          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-04-06 23:28:04          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-04-06 23:28:05          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-04-06 23:28:06          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-04-06 23:28:07          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-04-06 23:28:08          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-04-06 23:28:09          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-04-06 23:28:10          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-04-06 23:28:11          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-04-06 23:28:12          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-04-06 23:28:13          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-04-06 23:28:14          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-04-06 23:28:15          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-04-06 23:28:16          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-04-06 23:28:17          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-04-06 23:28:18          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2021-04-06 23:28:19          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
wait-for-it.sh: timeout occurred after waiting 20 seconds for localhost:11144
```

**Review by philipstanislaus — COMMENTED** [review]
LGTM

**Pull request merged**
