### PR TITLE
WIP: access struct's serialized bytes directly

### PR DESCRIPTION
**Pull request by denalimarsh**
Current commitment validation:
```solidity
abi.encodePacked(
                    commitmentContents.messages[i].nonce,
                    commitmentContents.messages[i].senderApplicationId,
                    commitmentContents.messages[i].targetApplicationAddress,
                    commitmentContents.messages[i].payload
);
contents = abi.encodePacked(contents, temp);
commitmentHash = keccak256(contents);
```

We can potentially avoid accessing each messages' fields by updating the commitment hash:
```solidity
keccak256(abi.encode(commitmentContents.messages));
```

The additional test case demonstrates the desired functionality. Right now the test suite isn't properly hashing the encoded bytes, even though the two sets of bytes are the same.

### CODE REVIEW

**Review by vgeddes — APPROVED** [review]
Looks great! I'll merge these changes into #237.

**Review by philipstanislaus — APPROVED** [review]
LGTM! 👍

**Comment by musnit** [comment]
@denalimarsh can you merge this and https://github.com/Snowfork/polkadot-ethereum/pull/250 and deal with conflicts/changes with IncentivizedReceiveChannel.sol -> IncentivizedInboundChannel.sol there?

**Comment by denalimarsh** [comment]
Closing in favor of https://github.com/Snowfork/polkadot-ethereum/pull/266

**Pull request closed without merging**
