### PR TITLE
Add types definition package

### PR DESCRIPTION
**Pull request by vgeddes**

### CODE REVIEW

**Comment by musnit** [comment]
can use it from test/../subclient.ts too plz

**Comment by musnit** [comment]
substrate currently has no way to automatically generate this right? has to be manually created?

**Comment by vgeddes** [comment]
> can use it from test/../subclient.ts too plz

This is just the first of several PRs, as this change has to be made in several phases:
* First add the types package to the monorepo
* Ask upstream to use our types package in the polkadot webapp
* Once they OK it, then follow up and make the necessary changes to get everything else to use our types package.

**Comment by vgeddes** [comment]
> substrate currently has no way to automatically generate this right? has to be manually created?

Correct. However there are long-term plans to update the SCALE codec to include type metadata. Thats a long way off though.

**Pull request merged**
